CREATE SCHEMA SCHEMA_MAIN;

CREATE  TABLE SCHEMA_MAIN.FACULTY ( 
	FACULTY_SHORT_NAME   CHAR(4) NOT NULL   ,
	FACULTY_NAME         VARCHAR(30) NOT NULL   ,
	CONSTRAINT PK_FACULTY PRIMARY KEY ( FACULTY_SHORT_NAME )
 );

CREATE  TABLE SCHEMA_MAIN.SUBJECT ( 
	SUBJECT_NR           VARCHAR(20) NOT NULL   ,
	SUBJECT_SEMESTER_LVL BIGINT NOT NULL   ,
	DEGREE_SHORT_NAME    CHAR(3) NOT NULL   ,
	SUBJECT_NAME         VARCHAR(60) NOT NULL   ,
	SUBJECT_ELECTIVE     CHAR(1) NOT NULL   ,
	SUBJECT_CURRICULUM   BIGINT NOT NULL   ,
	SUBJECT_SCHEDULE     BIGINT NOT NULL   ,
	SUBJECT_COMMENT      VARCHAR(255)    ,
	CONSTRAINT PK_SUBJECT PRIMARY KEY ( SUBJECT_NR )
 );

ALTER TABLE SCHEMA_MAIN.SUBJECT ADD CONSTRAINT CNS_SUBJECT_ELECTIVE CHECK ( SUBJECT_ELECTIVE IN ('P', 'W', 'Z') );

ALTER TABLE SCHEMA_MAIN.SUBJECT ADD CONSTRAINT CNS_SUBJECT_CURRICULUM_AND_SCHEDULE CHECK ( SUBJECT_CURRICULUM >= 0 AND SUBJECT_SCHEDULE >= 0 );

CREATE  TABLE SCHEMA_MAIN.ACADEMIC_STAFF ( 
	ACADEMIC_STAFF_ID    BIGINT NOT NULL   ,
	FIRST_NAME           VARCHAR(50) NOT NULL   ,
	LAST_NAME            VARCHAR(50) NOT NULL   ,
	ACADEMIC_STAFF_COMMENT VARCHAR(255)    ,
	FACULTY_SHORT_NAME   CHAR(4) NOT NULL   ,
	IS_PROF              BOOLEAN NOT NULL   ,
	CONSTRAINT PK_ACADEMIC_STAFF PRIMARY KEY ( ACADEMIC_STAFF_ID )
 );

CREATE  TABLE SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD ( 
	ACADEMIC_STAFF_ID    BIGINT NOT NULL   ,
	SEMESTER_NR          VARCHAR(8) NOT NULL   ,
	ACADEMIC_STAFF_REDUCTION DECIMAL(5,2) NOT NULL   ,
	ACADEMIC_STAFF_ROLE  CHAR(42) NOT NULL   ,
	CONSTRAINT PK_ACADEMIC_STAFF_WORKLOAD PRIMARY KEY ( SEMESTER_NR, ACADEMIC_STAFF_ID )
 );

ALTER TABLE SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD ADD CONSTRAINT CNS_ACADEMIC_STAFF_REDUCTION CHECK ( ACADEMIC_STAFF_REDUCTION >= 0 );

CREATE  TABLE SCHEMA_MAIN.DEGREE_PROGRAM ( 
	DEGREE_SHORT_NAME    CHAR(3) NOT NULL   ,
	DEGREE_NAME          VARCHAR(40) NOT NULL   ,
	FACULTY_SHORT_NAME   CHAR(3) NOT NULL   ,
	CONSTRAINT PK_DEGREE_PROGRAM PRIMARY KEY ( DEGREE_SHORT_NAME )
 );

CREATE  TABLE SCHEMA_MAIN.LECTURER ( 
	ACADEMIC_STAFF_ID    BIGINT NOT NULL   ,
	SUPERVISOR           BIGINT    ,
	CONSTRAINT PK_LECTURER PRIMARY KEY ( ACADEMIC_STAFF_ID ) 
 );

CREATE  TABLE SCHEMA_MAIN.COURSE ( 
	SUBJECT_NR           VARCHAR(20) NOT NULL   ,
	DEGREE_SHORT_NAME    CHAR(3) NOT NULL   ,
	COURSE_COMMENT       VARCHAR(255)    ,
	CONSTRAINT PK_COURSE PRIMARY KEY ( SUBJECT_NR, DEGREE_SHORT_NAME )
 );

CREATE  TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ( 
	COURSE_ASSIGNMENT_TERM VARCHAR(10) NOT NULL   ,
	SUBJECT_NR           VARCHAR(20) NOT NULL   ,
	ACADEMIC_STAFF_ID    BIGINT NOT NULL   ,
	TEACHING_HOURS       DECIMAL(5,2)   ,
	DEGREE_SHORT_NAME    CHAR(3) NOT NULL   ,
	CONSTRAINT PK PRIMARY KEY ( SUBJECT_NR, COURSE_ASSIGNMENT_TERM, ACADEMIC_STAFF_ID )
 );

ALTER TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ADD CONSTRAINT CNS_TEACHING_HOURS CHECK ( TEACHING_HOURS >= 0 );

ALTER TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ADD CONSTRAINT CNS_COURSE_ASSIGNMENT_TERM CHECK ( (COURSE_ASSIGNMENT_TERM LIKE 'WS%' OR COURSE_ASSIGNMENT_TERM LIKE 'SS%') );

ALTER TABLE SCHEMA_MAIN.ACADEMIC_STAFF ADD FOREIGN KEY FK_ACADEMIC_STAFF_FACULTY ( FACULTY_SHORT_NAME ) REFERENCES SCHEMA_MAIN.FACULTY( FACULTY_SHORT_NAME ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD ADD FOREIGN KEY FK_ACADEMIC_STAFF ( ACADEMIC_STAFF_ID ) REFERENCES SCHEMA_MAIN.ACADEMIC_STAFF( ACADEMIC_STAFF_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.COURSE ADD FOREIGN KEY FK_DEGREE_PROGRAM ( DEGREE_SHORT_NAME ) REFERENCES SCHEMA_MAIN.DEGREE_PROGRAM( DEGREE_SHORT_NAME ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.COURSE ADD FOREIGN KEY FK_COURSE_SUBJECT ( SUBJECT_NR ) REFERENCES SCHEMA_MAIN.SUBJECT( SUBJECT_NR ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ADD FOREIGN KEY FK_ACADEMIC_STAFF ( ACADEMIC_STAFF_ID ) REFERENCES SCHEMA_MAIN.ACADEMIC_STAFF( ACADEMIC_STAFF_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ADD FOREIGN KEY FK_CA_COURSE ( SUBJECT_NR, DEGREE_SHORT_NAME ) REFERENCES SCHEMA_MAIN.COURSE( SUBJECT_NR, DEGREE_SHORT_NAME ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.DEGREE_PROGRAM ADD FOREIGN KEY FK_DEGREE_PROGRAM_FACULTY ( FACULTY_SHORT_NAME ) REFERENCES SCHEMA_MAIN.FACULTY( FACULTY_SHORT_NAME ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.LECTURER ADD FOREIGN KEY FK_ACADEMIC_STAFF ( ACADEMIC_STAFF_ID ) REFERENCES SCHEMA_MAIN.ACADEMIC_STAFF( ACADEMIC_STAFF_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMENT ON TABLE SCHEMA_MAIN.FACULTY IS 'fullname of a faculty Informationstechnik';

COMMENT ON COLUMN SCHEMA_MAIN.FACULTY.FACULTY_SHORT_NAME IS 'short name for a faculty e.g. IT';

COMMENT ON COLUMN SCHEMA_MAIN.FACULTY.FACULTY_NAME IS 'fullname of a faculty Informationstechnik';



COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_NR IS 'SPO code, e.g. ''1053007-SWB''';

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_SEMESTER_LVL IS 'Semester Number';

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.DEGREE_SHORT_NAME IS 'Degree Short Name e.g SWB';

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_NAME IS 'Module name e.g IT Security';

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_ELECTIVE IS 'Elective Type e.g (P/W/Z)';

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_CURRICULUM IS 'required volume';

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_SCHEDULE IS 'the actual planned volume';

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_COMMENT IS 'comments for the subject';



COMMENT ON TABLE SCHEMA_MAIN.ACADEMIC_STAFF IS 'Course teaching persons';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.ACADEMIC_STAFF_ID IS 'An identifying number for the teacher.';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.FIRST_NAME IS 'Name of the teacher. E.g. "Jürgen Nonnast"';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.LAST_NAME IS 'Name of the teacher. E.g. "Jürgen Nonnast"';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.ACADEMIC_STAFF_COMMENT IS 'comments from the academic staff';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.FACULTY_SHORT_NAME IS 'which faculty he belongs to';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.IS_PROF IS 'if he or she is a prof';



COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD.SEMESTER_NR IS 'semester which the role start e.g. SS26';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD.ACADEMIC_STAFF_REDUCTION IS 'the workload he or she get credited for the role';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD.ACADEMIC_STAFF_ROLE IS 'the special role name';



COMMENT ON COLUMN SCHEMA_MAIN.DEGREE_PROGRAM.DEGREE_SHORT_NAME IS 'shortname of a degree e.g. SWB';

COMMENT ON COLUMN SCHEMA_MAIN.DEGREE_PROGRAM.DEGREE_NAME IS 'fullname of a degree e.g. Softwaretechnik und Medieninformatik';

COMMENT ON COLUMN SCHEMA_MAIN.DEGREE_PROGRAM.FACULTY_SHORT_NAME IS 'which faculty it belongs to e.g. IT';



COMMENT ON TABLE SCHEMA_MAIN.LECTURER IS
'A non-permanent teaching staff member, standardized in this document under the designation ''lecturer''.';

COMMENT ON COLUMN SCHEMA_MAIN.LECTURER.ACADEMIC_STAFF_ID IS 'academic staff id of the lecturer';

COMMENT ON COLUMN SCHEMA_MAIN.LECTURER.SUPERVISOR IS 'academic staff id of the supervisor of the lecturer';


COMMENT ON TABLE SCHEMA_MAIN.COURSE IS
'A class taught by a specific lecturer during a given semester, for instance, WS24/25.';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE.SUBJECT_NR IS 'FK from Subject';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE.DEGREE_SHORT_NAME IS 'shortname of a degree e.g. SWB';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE.COURSE_COMMENT IS 'comments for the course';


COMMENT ON COLUMN SCHEMA_MAIN.COURSE_ASSIGNMENT.COURSE_ASSIGNMENT_TERM IS
'The scheduled start term for the course offering (e.g. SS26)';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE_ASSIGNMENT.SUBJECT_NR IS 'subject number e.g. 1051001-SWB';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE_ASSIGNMENT.ACADEMIC_STAFF_ID IS 'the id of the teacher for the course';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE_ASSIGNMENT.TEACHING_HOURS IS 'the workload for the teacher';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE_ASSIGNMENT.DEGREE_SHORT_NAME IS 'short name for the degree e.g. SWB';

