CREATE SCHEMA SCHEMA_MAIN;

CREATE  TABLE SCHEMA_MAIN.FACULTY ( 
	FACULTY_SHORT_NAME   CHAR(4) NOT NULL   ,
	FACULTY_NAME         VARCHAR(30) NOT NULL   ,
	CONSTRAINT PK_FACULTY PRIMARY KEY ( FACULTY_SHORT_NAME )
 );

CREATE  TABLE SCHEMA_MAIN.SUBJECT ( 
	SUBJECT_NR           VARCHAR(20) NOT NULL   ,
	SUBJECT_SEMESTER_LVL BIGINT NOT NULL   ,
	DEGREE_SHORT_NAME    CHAR(3) NOT NULL   ,
	SUBJECT_NAME         VARCHAR(60) NOT NULL   ,
	SUBJECT_ELECTIVE     CHAR(1) NOT NULL   ,
	SUBJECT_CURRICULUM   BIGINT NOT NULL   ,
	SUBJECT_SCHEDULE     BIGINT NOT NULL   ,
	SUBJECT_COMMENT      VARCHAR(255)    ,
	CONSTRAINT PK_SUBJECT PRIMARY KEY ( SUBJECT_NR )
 );

ALTER TABLE SCHEMA_MAIN.SUBJECT ADD CONSTRAINT CNS_SUBJECT_ELECTIVE CHECK ( SUBJECT_ELECTIVE IN ('P', 'W', 'Z') );

ALTER TABLE SCHEMA_MAIN.SUBJECT ADD CONSTRAINT CNS_SUBJECT_CURRICULUM_AND_SCHEDULE CHECK ( SUBJECT_CURRICULUM >= 0 AND SUBJECT_SCHEDULE >= 0 );

CREATE  TABLE SCHEMA_MAIN.ACADEMIC_STAFF ( 
	ACADEMIC_STAFF_ID    BIGINT NOT NULL   ,
	FIRST_NAME           VARCHAR(50) NOT NULL   ,
	LAST_NAME            VARCHAR(50) NOT NULL   ,
	ACADEMIC_STAFF_COMMENT VARCHAR(255)    ,
	FACULTY_SHORT_NAME   CHAR(4) NOT NULL   ,
	IS_PROF              BOOLEAN NOT NULL   ,
	CONSTRAINT PK_ACADEMIC_STAFF PRIMARY KEY ( ACADEMIC_STAFF_ID )
 );

CREATE  TABLE SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD ( 
	ACADEMIC_STAFF_ID    BIGINT NOT NULL   ,
	SEMESTER_NR          VARCHAR(8) NOT NULL   ,
	ACADEMIC_STAFF_REDUCTION DECIMAL(5,2) NOT NULL   ,
	ACADEMIC_STAFF_ROLE  CHAR(42) NOT NULL   ,
	CONSTRAINT PK_ACADEMIC_STAFF_WORKLOAD PRIMARY KEY ( SEMESTER_NR, ACADEMIC_STAFF_ID )
 );

ALTER TABLE SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD ADD CONSTRAINT CNS_ACADEMIC_STAFF_REDUCTION CHECK ( ACADEMIC_STAFF_REDUCTION >= 0 );

CREATE  TABLE SCHEMA_MAIN.DEGREE_PROGRAM ( 
	DEGREE_SHORT_NAME    CHAR(3) NOT NULL   ,
	DEGREE_NAME          VARCHAR(40) NOT NULL   ,
	FACULTY_SHORT_NAME   CHAR(3) NOT NULL   ,
	CONSTRAINT PK_DEGREE_PROGRAM PRIMARY KEY ( DEGREE_SHORT_NAME )
 );

CREATE  TABLE SCHEMA_MAIN.LECTURER ( 
	ACADEMIC_STAFF_ID    BIGINT NOT NULL   ,
	SUPERVISOR           BIGINT    ,
	CONSTRAINT PK_LECTURER PRIMARY KEY ( ACADEMIC_STAFF_ID ) 
 );

CREATE  TABLE SCHEMA_MAIN.COURSE ( 
	SUBJECT_NR           VARCHAR(20) NOT NULL   ,
	DEGREE_SHORT_NAME    CHAR(3) NOT NULL   ,
	COURSE_COMMENT       VARCHAR(255)    ,
	CONSTRAINT PK_COURSE PRIMARY KEY ( SUBJECT_NR, DEGREE_SHORT_NAME )
 );

CREATE  TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ( 
	COURSE_ASSIGNMENT_TERM VARCHAR(10) NOT NULL   ,
	SUBJECT_NR           VARCHAR(20) NOT NULL   ,
	ACADEMIC_STAFF_ID    BIGINT NOT NULL   ,
	TEACHING_HOURS       DECIMAL(5,2)   ,
	DEGREE_SHORT_NAME    CHAR(3) NOT NULL   ,
	CONSTRAINT PK PRIMARY KEY ( SUBJECT_NR, COURSE_ASSIGNMENT_TERM, ACADEMIC_STAFF_ID )
 );

ALTER TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ADD CONSTRAINT CNS_TEACHING_HOURS CHECK ( TEACHING_HOURS >= 0 );

ALTER TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ADD CONSTRAINT CNS_COURSE_ASSIGNMENT_TERM CHECK ( (COURSE_ASSIGNMENT_TERM LIKE 'WS%' OR COURSE_ASSIGNMENT_TERM LIKE 'SS%') );

ALTER TABLE SCHEMA_MAIN.ACADEMIC_STAFF ADD FOREIGN KEY FK_ACADEMIC_STAFF_FACULTY ( FACULTY_SHORT_NAME ) REFERENCES SCHEMA_MAIN.FACULTY( FACULTY_SHORT_NAME ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.ACADEMIC_STAFF_WORKLOAD ADD FOREIGN KEY FK_ACADEMIC_STAFF ( ACADEMIC_STAFF_ID ) REFERENCES SCHEMA_MAIN.ACADEMIC_STAFF( ACADEMIC_STAFF_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.COURSE ADD FOREIGN KEY FK_DEGREE_PROGRAM ( DEGREE_SHORT_NAME ) REFERENCES SCHEMA_MAIN.DEGREE_PROGRAM( DEGREE_SHORT_NAME ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.COURSE ADD FOREIGN KEY FK_COURSE_SUBJECT ( SUBJECT_NR ) REFERENCES SCHEMA_MAIN.SUBJECT( SUBJECT_NR ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ADD FOREIGN KEY FK_ACADEMIC_STAFF ( ACADEMIC_STAFF_ID ) REFERENCES SCHEMA_MAIN.ACADEMIC_STAFF( ACADEMIC_STAFF_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.COURSE_ASSIGNMENT ADD FOREIGN KEY FK_CA_COURSE ( SUBJECT_NR, DEGREE_SHORT_NAME ) REFERENCES SCHEMA_MAIN.COURSE( SUBJECT_NR, DEGREE_SHORT_NAME ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.DEGREE_PROGRAM ADD FOREIGN KEY FK_DEGREE_PROGRAM_FACULTY ( FACULTY_SHORT_NAME ) REFERENCES SCHEMA_MAIN.FACULTY( FACULTY_SHORT_NAME ) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE SCHEMA_MAIN.LECTURER ADD FOREIGN KEY FK_ACADEMIC_STAFF ( ACADEMIC_STAFF_ID ) REFERENCES SCHEMA_MAIN.ACADEMIC_STAFF( ACADEMIC_STAFF_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_NR IS 'The number of the subject e.g 1051003';

COMMENT ON COLUMN SCHEMA_MAIN.SUBJECT.SUBJECT_SEMESTER_LVL IS 'The name of a subject. E.g. "Information Systems"';

COMMENT ON TABLE SCHEMA_MAIN.ACADEMIC_STAFF IS 'Course teaching persons';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.ACADEMIC_STAFF_ID IS 'An identifying number for the teacher.';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.FIRST_NAME IS 'Name of the teacher.
E.g. "Jürgen Nonnast"';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.LAST_NAME IS 'Name of the teacher.
E.g. "Jürgen Nonnast"';

COMMENT ON COLUMN SCHEMA_MAIN.ACADEMIC_STAFF.ACADEMIC_STAFF_COMMENT IS 'Optional instructor comments.';

COMMENT ON TABLE SCHEMA_MAIN.LECTURER IS 'A non-permanent teaching staff member, standardized in this document under the designation ''lecturer''.';

COMMENT ON COLUMN SCHEMA_MAIN.LECTURER.ACADEMIC_STAFF_ID IS 'The unique identifier for the instructor, serving as a foreign key referencing the Teacher table.';

COMMENT ON COLUMN SCHEMA_MAIN.LECTURER.SUPERVISOR IS 'Is used to assign a directly supervising professor to a specific lecturer';

COMMENT ON TABLE SCHEMA_MAIN.COURSE IS 'A class taught by a specific lecturer during a given semester, for instance, WS24/25.';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE.SUBJECT_NR IS 'The number of the subject e.g 1051003';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE.DEGREE_SHORT_NAME IS 'A unique alphanumeric code identifying the specific degree program (e.g., ''SWB'').';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE.COURSE_COMMENT IS 'Optional remark about the course.';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE_ASSIGNMENT.COURSE_ASSIGNMENT_TERM IS 'The designated start semester for the course offering (e.g., ''WS24/25'')';

COMMENT ON COLUMN SCHEMA_MAIN.COURSE_ASSIGNMENT.ACADEMIC_STAFF_ID IS 'An identifying number for the teacher.';

